In [ ]:
#@title Analysis of the labor market https://statistiques.pole-emploi.org/offres/offres?graph=1&fk=C&ss=1
#@markdown the goal of the project is to study the labor market, 

#@markdown ### Description
#@markdown Hello Doe has access job a labor market database via an API. This API allows us to collect all the information necessary to analyze the market. The goal of the challenge is to use this information to make it relevant for the development of our startup:

#@markdown - Optimize the conversion rate of business developers
#@markdown - Study the seasonality and territoriality of recruitment needs
#@markdown - Monitor the current state of the market which is the core of our business at Hello Doe.
#@markdown - Targeting sectors that are struggling to recruit.
#@markdown - Share our information, hello doe's mission is to help young people in the world of work, all information that can be shared with them will be published through news articles
#@markdown - Make predictions on the job market to be one step ahead
#@markdown - Hello Doe is a young startup and will be open to the student's initiative both for a choice of data analysis and for the direction chosen on the project.




#@markdown ### Request example :
#@markdown -  Select all information from 3 job seeker:  
#@markdown 'SELECT * from "76bfb51e-94cf-4912-a2d7-855f02678756" LIMIT 3'
#@markdown -  Count job request for each categories ordered decreasing: \\
#@markdown 'SELECT "ROME_PROFESSION_CARD_NAME", COUNT(1) from "76bfb51e-94cf-4912-a2d7-855f02678756" GROUP BY "ROME_PROFESSION_CARD_NAME" ORDER BY COUNT(1) DESC'


#@markdown IMPORTANT TABLES : \\
#@markdown Statistiques offres et demandes	Statistiques sur les offres et demandes d'emploi	266f691f-bce8-4443-808e-8e5aa125cf17
#@markdown Statistiques de la demande d'emploi (ex feb 2020= e0be680d-1864-4bae-9017-7c8ca7a7976b)
#@markdown Liste des offres d'emploi actives de Pôle Emploi	a94e94dd-33ab-4b81-873b-675bf306550e  (x3) 
#@markdown CF DOC 

#@markdown ### What we need : 
#@markdown 1)
#@markdown - Statistics about Jobs offer per Category per Region and per Season
#@markdown - Statistics Jobs request per Category per Region and per Season \\

#@markdown 2)
#@markdown - Sectors struggling to recruit \\

#@markdown 3)
#@markdown - Profil/skills needed by these sectors \\



#@markdown These statistics have to be available for all differents job categories and for "Hello Doe" jobs categories (job that all students can do)

#@markdown LINK to get your Token : https://script.google.com/macros/s/AKfycbz1zlHhk85BG0seMp7xb0OldmQ3lh8wz2BqD3zBV1VC9hORUwKZvArHGXpBYnIRdNXx/exec



#@markdown Pole Emploi documentation (infoTravail API) https://www.emploi-store-dev.fr/portail-developpeur-cms/home/catalogue-des-api/documentation-des-api/api/api-infotravail-v1/ckan.html;JSESSIONID_JAHIA=4F2EEDE73E7625873DA18CAF943C6047

In [ ]:
import urllib.parse
import requests
import numpy as np
import pandas as pd
from IPython.display import display

SqlRequest='SELECT "ROME_PROFESSION_CARD_NAME", COUNT(1) from "76bfb51e-94cf-4912-a2d7-855f02678756" GROUP BY "ROME_PROFESSION_CARD_NAME" ORDER BY COUNT(1) DESC'  #@param
token="deGgGfGgAJrJvGwFoFKnzaH7-KM" #@param
url='https://api.emploi-store.fr/partenaire/infotravail/v1/datastore_search_sql?sql='

In [ ]:
#@title Display ref Table Pole Emploi
def doc(token): 
  url='https://api.emploi-store.fr/partenaire/infotravail/v1/organization_show?id=digidata'
  API_URL=url
  token='Bearer '+token
  headers={'Authorization': token}
  response = requests.post(API_URL,headers=headers)
  json=response.json()
  results= json['result']['packages']
  InfoRequest={}
  listField=['title','id']
  for field in listField:
        listValue=[]
        for j in results:
          listValue.append(j[field])
        InfoRequest[field]= listValue
  return InfoRequest

print("PACKAGE ID Pole Emploi")
objetDoc=doc(token)
df = pd.DataFrame(objetDoc)
display(df)
print("LIST OF TABLE/RESSOURCE to find data")
for i in range(len(objetDoc['id'])):
  objet=docTable(objetDoc['id'][i],token)
  df = pd.DataFrame(objet)
  print(objetDoc['title'][i])
  display(df)

Table with ID Pole Emploi

                                               title                                    id
0                        Offres d’emploi anonymisées  80341a24-a451-49ec-b6b0-1b8756fe977d
1              Informations sur le marché du travail  a4f9e4dd-365e-4542-839c-a93a2448e388
2                Référentiel des agences Pôle emploi  445b746a-bbe0-456a-8bee-ea24498242d3
3              Statistiques sur le marché du travail  47dbbaba-c983-47df-bd9c-eaeec14bd834
4  Répertoire Opérationnel des Métiers et des Emp...  78f91db4-b3c0-400c-a68d-47df9387e5a7
5              Enquête Besoins en Main d’Œuvre (BMO)  521b5b3e-9bcc-4e8e-b6f1-2a0a0899989a

Offres d’emploi anonymisées

                                               name  ...                                    id
0                 Référentiel des états d'une offre  ...  362eb4aa-77a5-4e9f-a720-877dbbc024c7
1      Référentiel des expériences professionnelles  ...  386075a7-ad0b-42e2-8e59-8aeddb4b872a
2                 Référentiel des durées de contrat  ...  47e0bd60-0361-451b-87c7-24203b6fe6e2
3                Référentiel des natures de contrat  ...  167d1031-ce27-4c35-9d01-d0ee96d85ead
4                  Référentiel des types de contrat  ...  0e8e3591-0a8e-471f-ae80-86bbb3f1b23d
5                  Référentiel des types de salaire  ...  b8171079-c6eb-4928-9993-8363b960f894
6                 Référentiel des unités monétaires  ...  78234f42-d345-4bdb-b54c-3379424c6481
7                  Référentiel des sous-classes NAF  ...  55d1e9c6-8147-4508-9486-3829d9e6c862
8                    Référentiel des qualifications  ...  2cbf766c-f9a1-49f4-a17f-aeeb06ceb834
9             Référentiel des conditions d'exercice  ...  62baa80b-741a-4496-a4fb-9e9185ecbb93
10                   Référentiel des types horaires  ...  1a6b6cdd-9e72-4168-b565-80b30821954a
11               Référentiel des types de formation  ...  b065018a-c7b3-4652-989f-80b6eb2f6601
12            Référentiel des domaines de formation  ...  f4717749-70cd-421c-a7cd-0980cb40f176
13                Référentiel des niveaux de langue  ...  1d3a9970-eee8-49c3-af28-aca85c1b9913
14                     Référentiel des exigibilités  ...  e8e269f8-d146-464e-a5c4-3d72cc5c6cdf
15                          Référentiel des langues  ...  a9d180ff-2b80-428a-a80d-12831d0ae105
16               Référentiel des permis de conduire  ...  5ec148dc-192d-4216-8b3f-2386e7cba250
17              Référentiel des outils bureautiques  ...  0c52bb99-0709-45fa-bad5-79227d243652
18  Référentiel des niveaux de pratique bureautique  ...  198f977e-94fe-4207-8d8b-80fe3ff17a54
19           Référentiel des compléments de salaire  ...  1ea1885d-023d-413f-a933-a352d89666f5
20            Référentiel des mailles géographiques  ...  ba6027d6-eb57-4186-a8d1-88eeca96ac05
21                  Référentiel des sous-continents  ...  5eafaeaf-fa8d-433f-8489-42ddce9df2ef
22                       Référentiel des continents  ...  71ef763a-bd5b-4b18-ae89-6ea8ff9af23d
23        Référentiel des fréquences de déplacement  ...  7cf951c0-9965-4a4a-b88c-dd9e12f44449
24             Référentiel des types de déplacement  ...  27c906a0-4680-4622-9526-73c5754a8001
25  Référentiel des modes de présentation employeur  ...  100b864f-4124-4d19-b43a-1b65e3c40071
26                                  Offres d'emploi  ...  a94e94dd-33ab-4b81-873b-675bf306550e
27                                  Offres d'emploi  ...  421692f5-f342-4223-9c51-72a27dcaf51e
28                                  Offres d'emploi  ...  e49af0f2-8d00-4a54-9124-2f4107efa810

[29 rows x 3 columns]

Informations sur le marché du travail

                                              name  ...                                    id
0                       Canaux de reprise d'emploi  ...  2de172fc-c5f2-4aaf-bd42-c4c052a0c4e1
1                  Statistiques offres et demandes  ...  266f691f-bce8-4443-808e-8e5aa125cf17
2                               Salaires pratiqués  ...  d9090eaf-65cd-41cb-816f-7249897a3e51
3  Types de contrat utilisés pour les recrutements  ...  8b8aad68-539f-453d-8e8b-fb6c18e19fae
4                 Référentiel des bassins d'emploi  ...  f2df60da-517f-4650-b880-a8aa9e4989e2
5            Référentiel des canaux de recrutement  ...  edbef9d4-26ce-4e83-a62c-bd11bafd3530
6                 Référentiel des types de contrat  ...  b1c1aa6b-3973-4ec2-8d4f-6cf26498754d

[7 rows x 3 columns]

Référentiel des agences Pôle emploi

                             name  ...                                    id
0             Agences Pôle emploi  ...  3424cdfd-45e5-414d-b19f-477a24c443a8
1  Référentiel des types d'agence  ...  f5bf9ea8-acef-4283-af66-1fef5ffc6e39

[2 rows x 3 columns]

Statistiques sur le marché du travail

                                                  name  ...                                    id
0                       Référentiel des qualifications  ...  122c4e1c-b822-40b5-8f00-5446df082665
1      Statistiques de la demande d'emploi en mai 2015  ...  e85d10a4-78b0-4d37-bc25-f59d8fd33a21
2    Statistiques de la demande d'emploi en juillet...  ...  5abf4b52-cef8-441d-bb36-7b22116e0bef
3     Statistiques de la demande d'emploi en août 2015  ...  afde6f07-ea89-4f4a-9fab-7e47aae904ae
4    Statistiques de la demande d'emploi en septemb...  ...  47d5ab0c-c788-4e73-8d81-00991658bfc6
..                                                 ...  ...                                   ...
127  Statistiques de la demande d'emploi en févr. 2020  ...  e0be680d-1864-4bae-9017-7c8ca7a7976b
128   Statistiques de la demande d'emploi en oct. 2019  ...  03f85dc9-aa9d-4424-8acb-b7a0f4158674
129    Statistiques de la demande d'emploi en mai 2019  ...  58cdb0d3-4097-4f0b-81c9-17871f0097f1
130   Statistiques de la demande d'emploi en juin 2019  ...  a9dc0cd3-3ddf-47d4-a721-e400d15a37c4
131  Statistiques de la demande d'emploi en juil. 2019  ...  dff73043-1c3c-42f8-ae92-3e2936267658

[132 rows x 3 columns]

Répertoire Opérationnel des Métiers et des Emplois

                                                 name  ...                                    id
0                       Liens entre référentiels ROME  ...  794e460b-6679-4d0b-bfea-8cf4071b4687
1                        Référentiel des métiers ROME  ...  767d0c4a-277b-493c-84b7-00143933efce
2           Référentiel des environnements de travail  ...  e4b361db-5de4-4db4-9a7b-2774fdafa511
3                         Référentiel des compétences  ...  bb7c0638-2bc3-41d9-93aa-75205c288509
4                           Référentiel des activités  ...  6ecb44fe-c503-40c0-b724-985056fc6e5c
5              En-têtes des blocs sur les fiches ROME  ...  5efcae3e-638d-4091-91a2-ddf55a72d93e
6                        Référentiel des appellations  ...  7c7b90a4-11e6-4283-97f3-59dbf40d8e86
7                          Types de référentiels ROME  ...  a1a43a8c-fe41-4b86-ad7b-72ae64fa7422
8                          Textes sur les fiches ROME  ...  ca4478b2-3911-4f17-a868-782b976b5b5b
9         Mobilités possibles entre deux métiers ROME  ...  fee4d4ed-d765-4f5e-9fe0-293f84e69a74
10                     Blocs des fiches emploi-métier  ...  9222a7aa-1bdd-4ce4-a4b8-140c7a47ccdb
11                 Rubriques des fiches emploi-métier  ...  429b714d-70da-4c9d-b6b7-fc105f7da341
12               Codification RIASEC des métiers ROME  ...  28d596da-74d2-4195-9ac1-784cb51d6b69
13             Codification RIASEC des activités ROME  ...  ca00d690-3b55-4ad3-bc95-87f80d126f55
14                     Grands domaines professionnels  ...  e5eba2a1-d8f4-4762-abc2-cb8bb00686d4
15                            Domaines professionnels  ...  ad3b6d19-4aab-45c6-b9ea-c0a5b49b3e6e
16  Grands domaines et domaines professionnels des...  ...  aff724e0-cb7f-4ee0-a559-740d51331736
17                              Items des fiches ROME  ...  9b2ce3e6-5e8d-4f77-ac23-71c336880fe9
18                    Items associés aux métiers ROME  ...  cb02a635-daa0-4db8-b86d-4e8df45736fe
19  Métiers, grands domaines et domaines professio...  ...  e1ef71c2-c8e4-4aa6-89b3-2871dffd312b
20                              Arborescences du ROME  ...  eb15b29a-4c7c-4ede-b131-7dc3c8bbe026

[21 rows x 3 columns]

Enquête Besoins en Main d’Œuvre (BMO)

                                 name  ...                                    id
0  Référentiel des familles de métier  ...  94683478-6d99-4fa5-b016-74eb83f07343
1          Résultats enquête BMO 2014  ...  b8c6313f-4414-4866-b1f5-053158cf6b72
2          Résultats enquête BMO 2015  ...  5e1c194a-131d-4e73-a9b8-7b49c4e8615e
3          Résultats enquête BMO 2016  ...  6c74b2b7-8ec5-474a-8706-1069670c2035
4          Résultats enquête BMO 2017  ...  aab71292-a64f-403d-8f1a-63e4a2a557a8
5          Résultats enquête BMO 2018  ...  2dca07af-ab78-45c4-8c92-7b86b6db036e
6          Résultats enquête BMO 2019  ...  f5ed93cf-1626-47cc-90e4-13fb2cd40a7f
7          Résultats enquête BMO 2020  ...  6a645756-2f29-4ef9-af82-a2d88028403a

[8 rows x 3 columns]

6

In [ ]:

def docTable(id,token): 
  url='https://api.emploi-store.fr/partenaire/infotravail/v1/package_show?id='+id
  API_URL=url
  token='Bearer '+token
  headers={'Authorization': token}
  response = requests.post(API_URL,headers=headers)
  json=response.json()
  results= json['result']['resources']
  InfoRequest={}
  listField=['name','description','id']
  for field in listField:
        listValue=[]
        for j in results:
          listValue.append(j[field])
        InfoRequest[field]= listValue
  return InfoRequest

objetDoc=docTable('a4f9e4dd-365e-4542-839c-a93a2448e388',token)
df = pd.DataFrame(objetDoc)
df.style.set_caption('Top 10 Fields of Research by Aggregated Funding Amount')
df

                                              name  ...                                    id
0                       Canaux de reprise d'emploi  ...  2de172fc-c5f2-4aaf-bd42-c4c052a0c4e1
1                  Statistiques offres et demandes  ...  266f691f-bce8-4443-808e-8e5aa125cf17
2                               Salaires pratiqués  ...  d9090eaf-65cd-41cb-816f-7249897a3e51
3  Types de contrat utilisés pour les recrutements  ...  8b8aad68-539f-453d-8e8b-fb6c18e19fae
4                 Référentiel des bassins d'emploi  ...  f2df60da-517f-4650-b880-a8aa9e4989e2
5            Référentiel des canaux de recrutement  ...  edbef9d4-26ce-4e83-a62c-bd11bafd3530
6                 Référentiel des types de contrat  ...  b1c1aa6b-3973-4ec2-8d4f-6cf26498754d

[7 rows x 3 columns]

In [ ]:
def poleEmploiRequest(SqlRequest,token): 
   url='https://api.emploi-store.fr/partenaire/infotravail/v1/datastore_search_sql?sql='
   API_URL=url+urllib.parse.quote(SqlRequest)
   token='Bearer '+token
   headers={'Authorization': token}
   response = requests.post(API_URL,headers=headers)
   print(response)
   json=response.json()
   InfoRequest={}
   for i in json['result']['fields']:
        field=i['id']
        listValue=[]
        for j in response.json()['result']['records']:
          listValue.append(j[field])
        InfoRequest[field]= listValue
   return InfoRequest

In [ ]:
#'SELECT "ROME_PROFESSION_CARD_NAME", COUNT(1) from "76bfb51e-94cf-4912-a2d7-855f02678756" GROUP BY "ROME_PROFESSION_CARD_NAME" ORDER BY COUNT(1) DESC'
objectResponseRequest=poleEmploiRequest(SqlRequest,token)
df = pd.DataFrame(objectResponseRequest)
df

<Response [200]>

                             ROME_PROFESSION_CARD_NAME  count
0                          Assistance auprès d'enfants  23168
1                                  Nettoyage de locaux  17559
2                                 Services domestiques  13784
3               Magasinage et préparation de commandes  12831
4    Vente en habillement et accessoires de la pers...  12622
..                                                 ...    ...
525                                       Magistrature      4
526       Contrôle et inspection des Affaires Sociales      4
527          Conduite de machine de textiles nontissés      3
528  Représentation de l'Etat sur le territoire nat...      3
529   Conception - développement produits d'assurances      2

[530 rows x 2 columns]

In [ ]:
#@title Import CSV file from drive
import gspread
from oauth2client.client import GoogleCredentials
from google.colab import auth
auth.authenticate_user()

url= 'https://docs.google.com/spreadsheets/d/1B80-9Jgj6YenircZvggkj0g9m_gTLahXN__1Jw13CIM/edit#gid=0'
id='1B80-9Jgj6YenircZvggkj0g9m_gTLahXN__1Jw13CIM'
gc = gspread.authorize(GoogleCredentials.get_application_default())
worksheet=gc.open_by_key(id).sheet1
rows= worksheet.get_all_values()
print(rows)

[['ROME_PROFESSION_CARD_CODE', 'ROME_PROFESSION_CARD_NAME', 'Offre', 'Demande', ''], ['N1303', "Intervention technique d''exploitation logistique", '707', '1259', '1,780763791'], ['N1105', 'Manutention manuelle de charges', '1063', '6633', '6,239887112'], ['N1103', 'Magasinage et préparation de commandes', '3203', '12831', '4,005931939'], ['N1102', 'Déménagement', '143', '265', '1,853146853'], ['M1606', 'Saisie de données', '86', '512', '5,953488372'], ['M1603', 'Distribution de documents', '214', '739', '3,453271028'], ['M1601', 'Accueil et renseignements', '662', '5986', '9,042296073'], ['M1401', "Conduite d''enquêtes", '1190', '241', '0,2025210084'], ['K2501', 'Gardiennage de locaux', '189', '1381', '7,306878307'], ['K2303', 'Nettoyage des espaces urbains', '249', '1021', '4,100401606'], ['K2204', 'Nettoyage de locaux', '3350', '17559', '5,241492537'], ['K2202', 'Lavage de vitres', '138', '89', '0,6449275362'], ['K1304', 'Services domestiques', '4321', '13784', '3,190002314'], ['K1303', "Assistance auprès d''enfants", '1784', '23168', '12,98654709'], ['K1302', "Assistance auprès d''adultes", '5063', '9160', '1,809204029'], ['K1207', 'Intervention socioéducative', '2193', '2406', '1,097127223'], ['K1206', 'Intervention socioculturelle', '385', '1054', '2,737662338'], ['K1201', 'Action sociale', '1132', '1009', '0,8913427562'], ['I1201', "Entretien d''affichage et mobilier urbain", '64', '65', '1,015625'], ['H3302', "Opérations manuelles d''assemblage, tri ou emballage", '857', '6943', '8,101516919'], ['H1101', 'Assistance et support technique client', '190', '129', '0,6789473684'], ['G1803', 'Service en restauration', '2747', '5939', '2,161994904'], ['G1801', 'Café, bar brasserie', '635', '2985', '4,700787402'], ['G1703', 'Réception en hôtellerie', '794', '1493', '1,880352645'], ['G1702', 'Personnel du hall', '21', '68', '3,238095238'], ['G1701', 'Conciergerie en hôtellerie', '9', '36', '4'], ['G1605', 'Plonge en restauration', '764', '3669', '4,802356021'], ['G1604', 'Fabrication de crêpes ou pizzas', '535', '547', '1,022429907'], ['G1603', 'Personnel polyvalent en restauration', '1673', '4746', '2,836820084'], ['G1602', 'Personnel de cuisine', '4604', '6900', '1,498696785'], ['G1502', "Personnel polyvalent d''hôtellerie", '217', '343', '1,580645161'], ['G1501', "Personnel d''étage", '1047', '1753', '1,674307545'], ['G1206', 'Personnel technique des jeux', '2', '104', '52'], ['G1205', "Personnel d''attractions ou de structures de loisirs", '54', '74', '1,37037037'], ['G1203', "Animation de loisirs auprès d''enfants ou d''adolescents", '1590', '4286', '2,695597484'], ['G1202', "Animation d''activités culturelles ou ludiques", '348', '1453', '4,175287356'], ['G1201', "Accompagnement de voyages, d''activités culturelles ou sportives", '53', '533', '10,05660377'], ['G1102', 'Promotion du tourisme local', '19', '264', '13,89473684'], ['G1101', 'Accueil touristique', '132', '615', '4,659090909'], ['F1703', 'Maçonnerie', '3096', '6170', '1,992894057'], ['E1101', 'Animation de site multimédia', '105', '183', '1,742857143'], ['D1507', 'Mise en rayon libre-service', '1794', '8647', '4,819955407'], ['D1506', 'Marchandisage', '206', '100', '0,4854368932'], ['D1505', 'Personnel de caisse', '695', '6301', '9,06618705'], ['D1503', 'Management/gestion de rayon produits non alimentaires', '153', '502', '3,281045752'], ['D1502', 'Management/gestion de rayon produits alimentaires', '450', '559', '1,242222222'], ['D1501', 'Animation de vente', '175', '567', '3,24'], ['D1408', 'Téléconseil et télévente', '837', '2147', '2,565113501'], ['D1403', 'Relation commerciale auprès de particuliers', '2034', '1519', '0,7468043265'], ['D1401', 'Assistanat commercial', '2907', '5718', '1,966976264'], ['D1214', 'Vente en habillement et accessoires de la personne', '711', '12622', '17,75246132'], ['D1212', 'Vente en décoration et équipement du foyer', '1418', '3440', '2,425952045'], ['D1211', 'Vente en articles de sport et loisirs', '387', '2815', '7,273901809'], ['D1210', 'Vente en animalerie', '44', '376', '8,545454545'], ['D1209', 'Vente de végétaux', '654', '1091', '1,668195719'], ['D1205', "Nettoyage d''articles textiles ou cuirs", '115', '375', '3,260869565'], ['D1107', 'Vente en gros de produits frais', '29', '379', '13,06896552'], ['D1106', 'Vente en alimentation', '2130', '5443', '2,555399061'], ['B1301', "Décoration d''espaces de vente et d''exposition", '47', '180', '3,829787234'], ['A1503', 'Toilettage des animaux', '23', '141', '6,130434783'], ['A1501', 'Aide aux soins animaux', '48', '573', '11,9375'], ['A1403', "Aide d''élevage agricole et aquacole", '85', '293', '3,447058824'], ['A1402', 'Aide agricole de production légumière ou végétale', '110', '898', '8,163636364'], ['A1401', 'Aide agricole de production fruitière ou viticole', '136', '1702', '12,51470588'], ['A1204', 'Protection du patrimoine naturel', '7', '125', '17,85714286'], ['A1203', 'Aménagement et entretien des espaces verts', '2461', '7151', '2,905729378'], ['A1202', 'Entretien des espaces naturels', '84', '761', '9,05952381'], ['', '', '', '', ''], ['Total ', '', '63368', '212820', '5,43473679']]